conversion_factors = {"AUD": 1.5,
                      "GBP": 0.8,
                      "EUR": 0.9395,
                      "CAD": 1.33,
                      "CHF": 0.9202,
                      "JPY": 139.77,
                      "CNY": 7.13,
                      "INR": 82.55,
                      "BRL": 4.92,
                      "ZAR": 18.95,
                      "MXN": 17.35,
                      "KRW": 1302.70,
                      "TWD": 30.74,
                      "THB": 34.82,
                      "SGD": 1.3575,
                      "HKD": 7.85,
                      "NZD": 1.65,
                      "PHP": 56.11,
                      "MYR": 4.62,
                      "IDR": 14887.00,
                      "VND": 23495.00,
                      "RUB": 82.06,
                      "CZK": 22.01,
                      "PLN": 4.18,
                      "HUF": 344.26,
                      "RON": 4.62,
                      "SEK": 9.66,
                      "NOK": 10.97,
                      "DKK": 6.94,
                      "ISK": 140.09,
                      "HRK": 7.03933,
                      "TRY": 23.36,
                      "ILS": 3.61,
                      "AED": 3.6733,
                      "AFN": 77.34,
                      "ALL": 104.56,
                      "AMD": 475.04,
                      "ANG": 1.79,
                      "AOA": 425.00,
                      "ARS": 99.91,
                      "AWG": 1.79,
                      "AZN": 1.70,
                      "BAM": 1.95,
                      "BBD": 2.00,
                      "BDT": 84.63,
                      "BGN": 1.95,
                      "BHD": 0.377,
                      "BIF": 2125.00,
                      "BMD": 1.00,
                      "BND": 1.39,
                      "BOB": 6.96,
                      "BSD": 1.00,
                      "BTN": 69.88,
                      "BWP": 10.76,
                      "BYN": 2.50,
                      "BZD": 2.00,
                      "CDF": 1855.00,
                      "CLP": 850.00,
                      "COP": 3885.00,
                      "CRC": 605.00,
                      "CUP": 24.00,
                      "CVE": 93.99,
                      "DOP": 57.86,
                      "DZD": 147.00,
                      "EGP": 18.38,
                      "ERN": 15.00,
                      "ETB": 30.00,
                      "FJD": 2.20,
                      "FKP": 0.76,
                      "GEL": 3.00,
                      "GHS": 6.17,
                      "GIP": 0.76,
                      "GMD": 52.85,
                      "GNF": 9550.00,
                      "GTQ": 7.73,
                      "GYD": 209.00,
                      "HNL": 24.00,
                      "HTG": 124.00,
                      "IMP": 0.76,
                      "IQD": 1460.00,
                      "IRR": 42000.00,
                      "JMD": 150.00,
                      "JOD": 0.712,
                      "KES": 117.00,
                      "KGS": 84.00,
                      "KHR": 4075.00,
                      "KMF": 450.00,
                      "KPW": 170.00,
                      "KWD": 3.30,
                      "KYD": 1,
                      "LAK": 15000,
                      "LSL": 17,
                      "LTL": 3.45,
                      "MKD": 61.00,
                      "MGA": 3200.00,
                      "MVR": 15.40,
                      "MRU": 357.00,
                      "MUR": 42.00,
                      "MNT": 2800.00,
                      "MAD": 9.60,
                      "MZN": 60.00,
                      "NAD": 1480,
                      "NGN": 4110,
                      "NPR": 1170,
                      "OMR": 260,
                      "PAB": 100,
                      "PEN": 385,
                      "PGK": 340,
                      "PKR": 1860,
                      "PYG": 6800,
                      "QAR": 364,
                      "RSD": 1170,
                      "RWF": 880,
                      "SAR": 375,
                      "SBD": 240,
                      "SCR": 1380,
                      "SDG": 4470,
                      "SLL": 10000,
                      "SOS": 250,
                      "SRD": 210,
                      "STN": 200,
                      "SYP": 1250,
                      "SZL": 200,
                      "TJS": 1000,
                      "TMT": 300,
                      "TND": 280,
                      "TOP": 220,
                      "TTD": 650,
                      "TZS": 2300,
                      "UAH": 270,
                      "UGX": 3700,
                      "USD": 1,
                      "UYU": 460,
                      "UZS": 10000,
                      "VES": 450,
                      "VUV": 1150,
                      "WST": 250,
                      "YER": 2500,
                      "ZMW": 180
                      }

requests_list = ['request_nonesmoke', 'request_latecheckin',
                 'request_highfloor', 'request_largebed',
                 'request_twinbeds', 'request_airport', 'request_earlycheckin']

dummies = ['original_payment_type', 'charge_option']

columns_to_drop = ['origin_country_code',
                   'language',
                   'original_payment_method',
                   'request_nonesmoke',
                   'request_latecheckin',
                   'request_highfloor',
                   'request_largebed',
                   'request_twinbeds',
                   'request_airport',
                   'request_earlycheckin',
                   'original_payment_currency',
                   'hotel_brand_code',
                   'hotel_chain_code',
                   'hotel_city_code',
                   'hotel_chain_code',
                   'hotel_country_code',
                   'hotel_area_code',
                   'h_customer_id',
                   'customer_nationality',
                   'guest_nationality_country_name',
                   "checkout_date",
                   "checkin_date",
                   "booking_datetime",
                   "h_booking_id",
                   "hotel_id",
                   "hotel_country_code",
                   "cancellation_policy_code",
                   "hotel_live_date",
                   "accommadation_type_name"]

